name: Compile backports.lzma
on: [push, workflow_dispatch]
jobs:
  compile_backports_lzma:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 2.7
        uses: LizardByte/setup-python-action@master
        with:
          python-version: '2.7'
          
      - name: Install Microsoft Visual C++ Compiler for Python 2.7
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vc_redist.x86.exe -OutFile vc_redist.x86.exe
          Start-Process -Wait -FilePath .\vc_redist.x86.exe
          Remove-Item .\vc_redist.x86.exe

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython

      - name: Compile backports.lzma
        run: |
          python setup.py build_ext --inplace

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backports_lzma_compiled
          path: .
