name: Compile backports.lzma
on: [push, pull_request, workflow_dispatch]
jobs:
  compile_backports_lzma:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 2.7
        uses: LizardByte/setup-python-action@master
        with:
          python-version: '2.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython

      - name: Compile backports.lzma
        run: |
          python setup.py build_ext --inplace

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backports_lzma_compiled
          path: .
